name: Generate JSON

defaults:
  run:
    working-directory: workflow

on:
  workflow_dispatch:
    schedule:
      - cron: "30 20,21,22 * * 1-6"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - run: |
          git config --global user.name 'mskullcap'
          git config --global user.email '5277001+mskullcap@users.noreply.github.com'
          git commit --allow-empty -am "updating covid data"
          git push origin --force
